#!/bin/sh
# 
# Combines the 'header' code and 'footer' code with the parser
# code generated by greg from the grammar description into
# one file.
# 

set -eu

HEADER_ROW=$(grep -nF '/// header_code_here' pmh_parser_core.c | awk 'BEGIN{FS=":"};{print $1}')
case "$HEADER_ROW" in
    ''|*[!0-9]*)
        echo "Expected exactly one header_code_here marker in pmh_parser_core.c" >&2
        exit 1
        ;;
esac
HEADER_ROW_BEFORE=$((HEADER_ROW - 1))
HEADER_ROW_AFTER=$((HEADER_ROW + 1))

head -n ${HEADER_ROW_BEFORE} pmh_parser_core.c
cat pmh_parser_head.c
tail -n +${HEADER_ROW_AFTER} pmh_parser_core.c
cat pmh_parser_foot.c


